[package]
name = "friendly-polylux"
version = "0.1.0"
entrypoint = "friendly.typ"
authors = ["Andreas Kröpelin", "Enivex"]
license = "MIT"
description = "Metropolis style template for Polylux"
repository = "https://github.com/polylux-typ/friendly"
keywords = ["friendly", "polylux", "presentation", "slides", "slide", "talk", "lecture"]
categories = ["presentation"]

[template]
path = "template"
entrypoint = "slides.typ"
thumbnail = "thumbnail.png"
