#let www-white = box(image("www.svg", width: 1em), baseline: .2em)
#let www = box(image("www-black.svg", width: 1em))
#let email = box(image("email.svg", width: 1em))
#let github = box(image("github.svg", width: 1em))
#let down-arrow = box(image("down-arrow.svg", width: 1em))
#let up-arrow = box(image("up-arrow.svg", width: 1em))
#let right-arrow = box(image("right-arrow.svg", width: 1em), baseline: .2em)

// Creative Commons
#let cc-by-nc-nd = box(image("cc/by-nc-nd.svg", width: 1em))
#let cc-by-nc-sa = box(image("cc/by-nc-sa.svg", width: 1em))
#let cc-by = box(image("cc/by.svg", width: 1em))
#let cc = box(image("cc/cc.svg", width: 1em))
#let cc-nc-eu = box(image("cc/nc-eu.svg", width: 1em))
#let cc-nc-jp = box(image("cc/nc-jp.svg", width: 1em))
#let cc-nc = box(image("cc/nc.svg", width: 1em))
#let cc-nd = box(image("cc/nd.svg", width: 1em))
#let cc-pd = box(image("cc/pd.svg", width: 1em))
#let cc-remix = box(image("cc/remix.svg", width: 1em))
#let cc-sa = box(image("cc/sa.svg", width: 1em))
#let cc-sampling-plus = box(image("cc/sampling.plus.svg", width: 1em))
#let cc-sampling = box(image("cc/sampling.svg", width: 1em))
#let cc-share = box(image("cc/share.svg", width: 1em))
#let cc-zero = box(image("cc/zero.svg", width: 1em))
